/**
 * Canonical source of all MDLand template dropdown values.
 * Extracted verbatim from AC-IE *.md template HTML files.
 *
 * CRITICAL: All strings must match the template EXACTLY (case-sensitive,
 * including spaces and special characters).
 */

// ─── Types ───────────────────────────────────────────────────────────

export type Severity = "normal" | "mild" | "moderate" | "severe";

export interface ROMOption {
  readonly degrees: number;
  readonly severity: Severity;
}

export interface ROMMovementOptions {
  readonly name: string;
  readonly options: readonly ROMOption[];
}

export interface BodyPartMuscles {
  readonly tightness: readonly string[];
  readonly tenderness: readonly string[];
  readonly spasm: readonly string[];
}

export type BodyPartKey =
  | "LBP"
  | "NECK"
  | "SHOULDER"
  | "KNEE"
  | "ELBOW"
  | "HIP"
  | "THIGH";

// ─── Pain Types ──────────────────────────────────────────────────────

const PAIN_TYPES_WITH_PIN_NEEDLES = [
  "Dull",
  "Burning",
  "Freezing",
  "Shooting",
  "Tingling",
  "Stabbing",
  "Aching",
  "Squeezing",
  "Cramping",
  "pricking",
  "weighty",
  "cold",
  "pin & needles",
] as const;

const PAIN_TYPES_WITHOUT_PIN_NEEDLES = [
  "Dull",
  "Burning",
  "Freezing",
  "Shooting",
  "Tingling",
  "Stabbing",
  "Aching",
  "Squeezing",
  "Cramping",
  "pricking",
  "weighty",
  "cold",
] as const;

export const TEMPLATE_PAIN_TYPES: Record<BodyPartKey, readonly string[]> = {
  LBP: PAIN_TYPES_WITH_PIN_NEEDLES,
  NECK: PAIN_TYPES_WITH_PIN_NEEDLES,
  SHOULDER: PAIN_TYPES_WITH_PIN_NEEDLES,
  KNEE: PAIN_TYPES_WITH_PIN_NEEDLES,
  ELBOW: PAIN_TYPES_WITHOUT_PIN_NEEDLES,
  HIP: PAIN_TYPES_WITH_PIN_NEEDLES,
  THIGH: PAIN_TYPES_WITH_PIN_NEEDLES,
} as const;

// ─── Muscles ─────────────────────────────────────────────────────────

const LBP_MUSCLES = [
  "iliocostalis",
  "spinalis",
  "longissimus",
  "Iliopsoas Muscle",
  "Quadratus Lumborum",
  "Gluteal Muscles",
  "The Multifidus muscles",
] as const;

const NECK_MUSCLES = [
  "Scalene anterior / med / posterior",
  "Levator Scapulae",
  "Trapezius",
  "sternocleidomastoid muscles",
] as const;

const SHOULDER_MUSCLES = [
  "upper trapezius",
  "greater tuberosity",
  "lesser tuberosity",
  "AC joint",
  "levator scapula",
  "rhomboids",
  "middle deltoid",
  "deltoid ant fibres",
  "bicep long head",
  "supraspinatus",
  "triceps short head",
] as const;

const KNEE_MUSCLES = [
  "Gluteus Maximus",
  "Gluteus medius / minimus",
  "Piriformis muscle",
  "Quadratus femoris",
  "Adductor longus/ brev/ magnus",
  "Iliotibial Band ITB",
  "Rectus Femoris",
  "Gastronemius muscle",
  "Hamstrings muscle group",
  "Tibialis Post/ Anterior",
  "Plantar Fasciitis",
  "Intrinsic Foot Muscle group",
  "Achilles Tendon",
] as const;

const ELBOW_TIGHTNESS_MUSCLES = [
  "Lattisimus dorsi",
  "Internal oblique",
  "External oblique",
  "Erector spinae",
  "Hamstrings",
  "Gluteus Maximus",
] as const;

const ELBOW_TENDERNESS_MUSCLES = [
  "Lattisimus dorsi",
  "Internal oblique",
  "External oblique",
  "Erector spinae",
  "Hamstrings",
  "Gluteus Maximus",
  "Illiac Crest",
  "s2-s4",
  "L2-L5",
] as const;

const HIP_THIGH_MUSCLES = [
  "greater tubercle",
  "lesser tubercle",
  "piriformis",
  "gluteus maximus",
  "iliopsoas",
  "TFL",
  "IT band",
  "quadriceps",
  "rectus femoris",
  "hamstrings",
] as const;

const HIP_THIGH_SPASM_MUSCLES = [
  "Quadratus Lumborum",
  "Tensor Fascia Latae",
  "Piriformis",
] as const;

export const TEMPLATE_MUSCLES: Record<BodyPartKey, BodyPartMuscles> = {
  LBP: {
    tightness: LBP_MUSCLES,
    tenderness: LBP_MUSCLES,
    spasm: LBP_MUSCLES,
  },
  NECK: {
    tightness: NECK_MUSCLES,
    tenderness: NECK_MUSCLES,
    spasm: NECK_MUSCLES,
  },
  SHOULDER: {
    tightness: SHOULDER_MUSCLES,
    tenderness: SHOULDER_MUSCLES,
    spasm: SHOULDER_MUSCLES,
  },
  KNEE: {
    tightness: KNEE_MUSCLES,
    tenderness: KNEE_MUSCLES,
    spasm: KNEE_MUSCLES,
  },
  ELBOW: {
    tightness: ELBOW_TIGHTNESS_MUSCLES,
    tenderness: ELBOW_TENDERNESS_MUSCLES,
    spasm: ELBOW_TIGHTNESS_MUSCLES,
  },
  HIP: {
    tightness: HIP_THIGH_MUSCLES,
    tenderness: HIP_THIGH_MUSCLES,
    spasm: HIP_THIGH_SPASM_MUSCLES,
  },
  THIGH: {
    tightness: HIP_THIGH_MUSCLES,
    tenderness: HIP_THIGH_MUSCLES,
    spasm: HIP_THIGH_SPASM_MUSCLES,
  },
} as const;

// ─── ROM Helper ──────────────────────────────────────────────────────

function rom(degrees: number, severity: Severity): ROMOption {
  return { degrees, severity };
}

function movement(
  name: string,
  options: readonly ROMOption[],
): ROMMovementOptions {
  return { name, options };
}

// ─── ROM Data ────────────────────────────────────────────────────────

const LBP_ROM: readonly ROMMovementOptions[] = [
  movement("Flexion", [
    rom(90, "normal"),
    rom(85, "normal"),
    rom(80, "normal"),
    rom(75, "mild"),
    rom(70, "mild"),
    rom(65, "mild"),
    rom(60, "moderate"),
    rom(55, "moderate"),
    rom(50, "moderate"),
    rom(45, "moderate"),
    rom(40, "moderate"),
    rom(35, "severe"),
    rom(30, "severe"),
    rom(25, "severe"),
    rom(15, "severe"),
    rom(10, "severe"),
    rom(5, "severe"),
  ]),
  movement("Extension", [
    rom(30, "normal"),
    rom(25, "mild"),
    rom(20, "moderate"),
    rom(15, "moderate"),
    rom(10, "severe"),
    rom(5, "severe"),
  ]),
  movement("Rotation to Right", [
    rom(30, "normal"),
    rom(25, "mild"),
    rom(20, "moderate"),
    rom(15, "moderate"),
    rom(10, "severe"),
    rom(5, "severe"),
  ]),
  movement("Rotation to Left", [
    rom(30, "normal"),
    rom(25, "mild"),
    rom(20, "moderate"),
    rom(15, "moderate"),
    rom(10, "severe"),
    rom(5, "severe"),
  ]),
  movement("Flexion to the Right", [
    rom(30, "normal"),
    rom(25, "mild"),
    rom(20, "moderate"),
    rom(15, "moderate"),
    rom(10, "severe"),
    rom(5, "severe"),
  ]),
  movement("Flexion to the Left", [
    rom(30, "normal"),
    rom(25, "mild"),
    rom(20, "moderate"),
    rom(15, "moderate"),
    rom(10, "severe"),
    rom(5, "severe"),
  ]),
] as const;

const NECK_ROM: readonly ROMMovementOptions[] = [
  movement("Extension", [
    rom(5, "severe"),
    rom(10, "severe"),
    rom(15, "severe"),
    rom(20, "moderate"),
    rom(25, "moderate"),
    rom(30, "moderate"),
    rom(35, "mild"),
    rom(40, "mild"),
    rom(45, "normal"),
    rom(55, "normal"),
    rom(65, "normal"),
  ]),
  movement("Flexion", [
    rom(5, "severe"),
    rom(10, "severe"),
    rom(15, "severe"),
    rom(20, "moderate"),
    rom(25, "moderate"),
    rom(30, "mild"),
    rom(35, "mild"),
    rom(40, "normal"),
    rom(50, "normal"),
  ]),
  movement("Rotation to Right", [
    rom(10, "severe"),
    rom(15, "severe"),
    rom(20, "severe"),
    rom(25, "severe"),
    rom(30, "moderate"),
    rom(35, "moderate"),
    rom(40, "moderate"),
    rom(45, "moderate"),
    rom(50, "mild"),
    rom(55, "mild"),
    rom(60, "mild"),
    rom(65, "mild"),
    rom(70, "normal"),
  ]),
  movement("Rotation to Left", [
    rom(10, "severe"),
    rom(15, "severe"),
    rom(20, "severe"),
    rom(25, "severe"),
    rom(30, "moderate"),
    rom(35, "moderate"),
    rom(40, "moderate"),
    rom(45, "moderate"),
    rom(50, "mild"),
    rom(55, "mild"),
    rom(60, "mild"),
    rom(65, "mild"),
    rom(70, "normal"),
  ]),
  movement("Lateral Flexion to the Right", [
    rom(10, "severe"),
    rom(15, "severe"),
    rom(20, "moderate"),
    rom(25, "moderate"),
    rom(30, "mild"),
    rom(35, "mild"),
    rom(40, "normal"),
  ]),
  movement("Lateral Flexion to the Left", [
    rom(10, "severe"),
    rom(15, "severe"),
    rom(20, "moderate"),
    rom(25, "moderate"),
    rom(30, "mild"),
    rom(35, "mild"),
    rom(40, "normal"),
  ]),
] as const;

const SHOULDER_ROM: readonly ROMMovementOptions[] = [
  movement("Abduction", [
    rom(180, "normal"),
    rom(175, "normal"),
    rom(170, "normal"),
    rom(165, "mild"),
    rom(160, "mild"),
    rom(155, "mild"),
    rom(150, "mild"),
    rom(145, "moderate"),
    rom(140, "moderate"),
    rom(135, "moderate"),
    rom(130, "moderate"),
    rom(125, "moderate"),
    rom(120, "moderate"),
    rom(115, "moderate"),
    rom(110, "moderate"),
    rom(105, "moderate"),
    rom(100, "moderate"),
    rom(95, "moderate"),
    rom(90, "severe"),
    rom(85, "severe"),
    rom(80, "severe"),
    rom(75, "severe"),
    rom(70, "severe"),
    rom(65, "severe"),
    rom(60, "severe"),
    rom(55, "severe"),
    rom(50, "severe"),
    rom(45, "severe"),
    rom(40, "severe"),
    rom(35, "severe"),
    rom(30, "severe"),
    rom(25, "severe"),
    rom(20, "severe"),
    rom(15, "severe"),
    rom(10, "severe"),
    rom(5, "severe"),
  ]),
  movement("Horizontal Adduction", [
    rom(45, "normal"),
    rom(40, "normal"),
    rom(35, "normal"),
    rom(30, "normal"),
    rom(25, "mild"),
    rom(20, "mild"),
    rom(15, "moderate"),
    rom(10, "moderate"),
    rom(5, "severe"),
  ]),
  movement("Flexion", [
    rom(180, "normal"),
    rom(175, "normal"),
    rom(170, "normal"),
    rom(165, "mild"),
    rom(160, "mild"),
    rom(155, "mild"),
    rom(150, "mild"),
    rom(145, "moderate"),
    rom(140, "moderate"),
    rom(135, "moderate"),
    rom(130, "moderate"),
    rom(125, "moderate"),
    rom(120, "moderate"),
    rom(115, "moderate"),
    rom(110, "moderate"),
    rom(105, "moderate"),
    rom(100, "moderate"),
    rom(95, "moderate"),
    rom(90, "severe"),
    rom(85, "severe"),
    rom(80, "severe"),
    rom(75, "severe"),
    rom(70, "severe"),
    rom(65, "severe"),
    rom(60, "severe"),
    rom(55, "severe"),
    rom(50, "severe"),
    rom(45, "severe"),
    rom(40, "severe"),
    rom(35, "severe"),
    rom(30, "severe"),
    rom(25, "severe"),
    rom(20, "severe"),
    rom(15, "severe"),
    rom(10, "severe"),
    rom(5, "severe"),
  ]),
  movement("Extension", [
    rom(5, "severe"),
    rom(10, "severe"),
    rom(15, "severe"),
    rom(20, "moderate"),
    rom(25, "moderate"),
    rom(30, "moderate"),
    rom(35, "moderate"),
    rom(40, "mild"),
    rom(45, "mild"),
    rom(50, "mild"),
    rom(55, "normal"),
    rom(60, "normal"),
  ]),
  movement("External rotation", [
    rom(90, "normal"),
    rom(85, "normal"),
    rom(80, "normal"),
    rom(75, "mild"),
    rom(70, "mild"),
    rom(65, "mild"),
    rom(60, "moderate"),
    rom(55, "moderate"),
    rom(50, "moderate"),
    rom(45, "moderate"),
    rom(40, "moderate"),
    rom(35, "severe"),
    rom(30, "severe"),
    rom(25, "severe"),
    rom(15, "severe"),
    rom(10, "severe"),
    rom(5, "severe"),
  ]),
  movement("Internal rotation", [
    rom(90, "normal"),
    rom(85, "normal"),
    rom(80, "normal"),
    rom(75, "mild"),
    rom(70, "mild"),
    rom(65, "mild"),
    rom(60, "moderate"),
    rom(55, "moderate"),
    rom(50, "moderate"),
    rom(45, "moderate"),
    rom(40, "moderate"),
    rom(35, "severe"),
    rom(30, "severe"),
    rom(25, "severe"),
    rom(15, "severe"),
    rom(10, "severe"),
    rom(5, "severe"),
  ]),
] as const;

const KNEE_ROM: readonly ROMMovementOptions[] = [
  movement("Flexion", [
    rom(130, "normal"),
    rom(125, "normal"),
    rom(120, "normal"),
    rom(115, "mild"),
    rom(110, "mild"),
    rom(105, "mild"),
    rom(100, "moderate"),
    rom(95, "moderate"),
    rom(90, "moderate"),
    rom(85, "moderate"),
    rom(80, "moderate"),
    rom(75, "moderate"),
    rom(70, "moderate"),
    rom(65, "severe"),
    rom(60, "severe"),
    rom(55, "severe"),
    rom(50, "severe"),
    rom(45, "severe"),
    rom(40, "severe"),
    rom(35, "severe"),
    rom(30, "severe"),
    rom(25, "severe"),
  ]),
  movement("Extension", [rom(0, "normal"), rom(-5, "severe")]),
] as const;

const ELBOW_ROM: readonly ROMMovementOptions[] = [
  movement("Flexion", [
    rom(150, "normal"),
    rom(145, "normal"),
    rom(140, "normal"),
    rom(135, "normal"),
    rom(130, "normal"),
    rom(125, "normal"),
    rom(120, "normal"),
    rom(115, "mild"),
    rom(110, "mild"),
    rom(105, "mild"),
    rom(100, "mild"),
    rom(95, "mild"),
    rom(90, "mild"),
    rom(85, "moderate"),
    rom(80, "moderate"),
    rom(75, "moderate"),
    rom(70, "moderate"),
    rom(65, "moderate"),
    rom(60, "moderate"),
    rom(55, "moderate"),
    rom(50, "moderate"),
    rom(45, "moderate"),
    rom(40, "moderate"),
    rom(35, "severe"),
    rom(30, "severe"),
    rom(25, "severe"),
    rom(20, "severe"),
    rom(15, "severe"),
    rom(10, "severe"),
    rom(5, "severe"),
    rom(0, "severe"),
  ]),
  movement("Extension", [rom(10, "normal"), rom(5, "mild")]),
  movement("Left side flexion", [
    rom(85, "normal"),
    rom(80, "normal"),
    rom(75, "normal"),
    rom(70, "normal"),
    rom(65, "normal"),
    rom(60, "normal"),
    rom(55, "normal"),
    rom(50, "normal"),
    rom(45, "mild"),
    rom(40, "mild"),
    rom(35, "moderate"),
    rom(30, "moderate"),
    rom(25, "moderate"),
    rom(20, "moderate"),
    rom(15, "severe"),
    rom(10, "severe"),
    rom(5, "severe"),
  ]),
  movement("Rt side flexion", [
    rom(85, "normal"),
    rom(80, "normal"),
    rom(75, "normal"),
    rom(70, "normal"),
    rom(65, "normal"),
    rom(60, "normal"),
    rom(55, "normal"),
    rom(50, "normal"),
    rom(45, "mild"),
    rom(40, "mild"),
    rom(35, "moderate"),
    rom(30, "moderate"),
    rom(25, "moderate"),
    rom(20, "moderate"),
    rom(15, "severe"),
    rom(10, "severe"),
    rom(5, "severe"),
  ]),
  movement("Left side rotation", [
    rom(85, "normal"),
    rom(80, "normal"),
    rom(75, "normal"),
    rom(70, "normal"),
    rom(65, "normal"),
    rom(60, "normal"),
    rom(55, "normal"),
    rom(50, "normal"),
    rom(45, "mild"),
    rom(40, "mild"),
    rom(35, "moderate"),
    rom(30, "moderate"),
    rom(25, "moderate"),
    rom(20, "moderate"),
    rom(15, "severe"),
    rom(10, "severe"),
    rom(5, "severe"),
  ]),
  movement("Right side rotation", [
    rom(85, "normal"),
    rom(80, "normal"),
    rom(75, "normal"),
    rom(70, "normal"),
    rom(65, "normal"),
    rom(60, "normal"),
    rom(55, "normal"),
    rom(50, "normal"),
    rom(45, "mild"),
    rom(40, "mild"),
    rom(35, "moderate"),
    rom(30, "moderate"),
    rom(25, "moderate"),
    rom(20, "moderate"),
    rom(15, "severe"),
    rom(10, "severe"),
    rom(5, "severe"),
  ]),
] as const;

const HIP_ROM: readonly ROMMovementOptions[] = [
  movement("Abduction", [
    rom(30, "normal"),
    rom(25, "normal"),
    rom(20, "mild"),
    rom(15, "mild"),
    rom(10, "moderate"),
    rom(5, "severe"),
  ]),
  movement("Flexion", [
    rom(130, "normal"),
    rom(120, "normal"),
    rom(110, "normal"),
    rom(100, "mild"),
    rom(90, "mild"),
    rom(80, "mild"),
    rom(70, "moderate"),
    rom(60, "moderate"),
    rom(50, "moderate"),
    rom(40, "severe"),
    rom(30, "severe"),
    rom(20, "severe"),
    rom(10, "severe"),
  ]),
  movement("Extension", [
    rom(30, "normal"),
    rom(25, "normal"),
    rom(20, "mild"),
    rom(15, "moderate"),
    rom(10, "moderate"),
    rom(5, "severe"),
  ]),
  movement("External rotation", [
    rom(5, "severe"),
    rom(10, "severe"),
    rom(15, "severe"),
    rom(20, "moderate"),
    rom(25, "moderate"),
    rom(30, "mild"),
    rom(35, "mild"),
    rom(40, "normal"),
    rom(45, "normal"),
  ]),
  movement("Internal rotation", [
    rom(5, "severe"),
    rom(10, "severe"),
    rom(15, "severe"),
    rom(20, "moderate"),
    rom(25, "moderate"),
    rom(30, "mild"),
    rom(35, "mild"),
    rom(40, "normal"),
  ]),
] as const;

const THIGH_ROM: readonly ROMMovementOptions[] = [
  movement("Abduction", [
    rom(30, "normal"),
    rom(25, "normal"),
    rom(20, "mild"),
    rom(15, "mild"),
    rom(10, "moderate"),
    rom(5, "severe"),
  ]),
  movement("Flexion", [
    rom(130, "normal"),
    rom(120, "normal"),
    rom(110, "normal"),
    rom(100, "mild"),
    rom(90, "mild"),
    rom(80, "mild"),
    rom(70, "moderate"),
    rom(60, "moderate"),
    rom(50, "moderate"),
    rom(40, "severe"),
    rom(30, "severe"),
    rom(20, "severe"),
    rom(10, "severe"),
  ]),
  movement("Extension", [
    rom(30, "normal"),
    rom(25, "normal"),
    rom(20, "mild"),
    rom(15, "moderate"),
    rom(10, "moderate"),
    rom(5, "severe"),
  ]),
] as const;

export const TEMPLATE_ROM: Record<BodyPartKey, readonly ROMMovementOptions[]> =
  {
    LBP: LBP_ROM,
    NECK: NECK_ROM,
    SHOULDER: SHOULDER_ROM,
    KNEE: KNEE_ROM,
    ELBOW: ELBOW_ROM,
    HIP: HIP_ROM,
    THIGH: THIGH_ROM,
  } as const;

// ─── ADL ─────────────────────────────────────────────────────────────

export const TEMPLATE_ADL: Record<BodyPartKey, readonly string[]> = {
  LBP: [
    "performing household chores",
    "working long time in front of computer",
    "long hours of driving",
    "doing laundry",
    "Cooking",
    "Going up and down stairs",
    "Lifting objects",
    "Bending over to wear/tie a shoe",
    "Rising from a chair",
    "Standing for long periods of time",
    "Walking for long periods of time",
    "sitting for long periods of time",
    "Getting out of bed",
    "standing for cooking",
  ],
  NECK: [
    "gargling",
    "looking down watching steps",
    "turning the head when crossing the street",
    "tilting head to talking the phone",
    "sit and watching TV over 20 mins",
    "reading newspaper/book",
    "performing household chores",
    "carry/handing grocery bags",
    "cooking",
    "doing laundry",
    "washing hair",
    "showering",
    "running/jumping/participating in physical exercise",
    "driving",
  ],
  SHOULDER: [
    "holding the pot for cooking",
    "performing household chores",
    "working long time in front of computer",
    "long hours of driving",
    "pushing/pulling cart, box, door",
    "doing laundry",
    "handing/carrying moderate objects",
    "put on/take off the clothes",
    "reach top of cabinet to get object(s)",
    "reach to back to unzip",
    "raising up the hand to comb hair",
    "touch opposite side shoulder to put coat on",
    "abduct arm get the objects from other people",
    "adduction arm to put pant on",
  ],
  KNEE: [
    "performing household chores",
    "long hours of driving",
    "Going up and down stairs",
    "Bending over to wear/tie a shoe",
    "Rising from a chair",
    "Standing for long periods of time",
    "Walking for long periods of time",
    "Getting out of bed",
    "standing for cooking",
    "bending knee to sit position",
    "bending down put in/out of the shoes",
  ],
  ELBOW: [
    "holding the pot for cooking",
    "performing household chores",
    "working long time in front of computer",
    "long hours of driving",
    "pushing/pulling cart, box, door",
    "doing laundry",
    "handing/carrying moderate objects",
    "put on/take off the clothes",
    "reach top of cabinet to get object(s)",
    "reach to back to unzip",
    "raising up the hand to comb hair",
    "touch opposite side shoulder to put coat on",
    "abduct arm get the objects from other people",
    "adduction arm to put pant on",
  ],
  HIP: [
    "performing household chores",
    "working long time in front of computer",
    "long hours of driving",
    "doing laundry",
    "Cooking",
    "Sitting or standing for long periods of time",
    "Going up and down stairs",
    "Lifting objects",
    "Bending over to wear/tie a shoe",
    "Rising from a chair",
  ],
  THIGH: [
    "performing household chores",
    "get out/in the chair or bed",
    "standing without any help",
    "standing long hours during work",
    "standing for cooking",
    "standing over 20 mins",
    "working long time in front of computer",
    "long hours of driving",
    "sitting over 30 mins",
    "walking over 15 mins",
    "go up/down stairs",
    "pushing/pulling cart, box, door",
    "doing laundry",
    "bending down put in/out of the shoes",
    "bend forward get object from floor",
    "handing/carrying moderate objects",
  ],
} as const;

// ─── Aggravating Factors ─────────────────────────────────────────────

export const TEMPLATE_AGGRAVATING: Record<BodyPartKey, readonly string[]> = {
  LBP: [
    "any strenuous activities",
    "repetitive motions",
    "poor sleep",
    "mental stress",
    "extension",
    "flexion",
    "abduction",
    "adduction",
    "internal rotation",
    "external rotation",
    "sleep to the side",
    "Standing after sitting for long time",
    "Stair climbing",
    "Sitting on a low chair",
    "Sitting cross leg",
    "Prolong walking",
  ],
  NECK: [
    "any strenuous activities",
    "repetitive motions",
    "poor sleep",
    "mental stress",
    "extension",
    "flexion",
    "abduction",
    "adduction",
    "internal rotation",
    "external rotation",
    "sleep to the side",
    "Standing after sitting for long time",
    "Stair climbing",
    "Sitting on a low chair",
    "Sitting cross leg",
    "prolonged walking",
    "prolonged standing",
    "prolonged sitting",
    "lifted heavy objects",
  ],
  SHOULDER: [
    "any strenuous activities",
    "repetitive motions",
    "push the door",
    "extension",
    "flexion",
    "abduction",
    "adduction",
    "internal rotation",
    "external rotation",
    "sleep to the side",
    "Lifting heavy objects",
    "Overhead activities",
  ],
  KNEE: [
    "any strenuous activities",
    "repetitive motions",
    "poor sleep",
    "mental stress",
    "extension",
    "flexion",
    "abduction",
    "adduction",
    "internal rotation",
    "external rotation",
    "sleep to the side",
    "Standing after sitting for long time",
    "Stair climbing",
    "Sitting on a low chair",
    "Sitting cross leg",
    "Prolong walking",
  ],
  ELBOW: [
    "any strenuous activities",
    "repetitive motions",
    "poor sleep",
    "mental stress",
    "cold weather",
    "push the door",
    "extension",
    "flexion",
    "abduction",
    "adduction",
    "internal rotation",
    "external rotation",
    "sleep to the side",
  ],
  HIP: [
    "any strenuous activities",
    "repetitive motions",
    "poor sleep",
    "mental stress",
    "extension",
    "flexion",
    "abduction",
    "adduction",
    "internal rotation",
    "external rotation",
    "sleep to the side",
    "Prolonge walking",
    "Standing after sitting for long time",
    "Stair climbing",
    "Sitting on a low chair",
    "Sitting cross leg",
  ],
  THIGH: [
    "prolonged walking",
    "prolonged sitting",
    "prolonged standing",
    "sit to stand",
    "lifting",
    "repetitive motions",
    "stress emotion",
    "exposure to cold air",
    "poor sleep",
    "flexion",
    "extension",
    "rotation to right",
    "rotation to left",
    "lateral flexion to right",
    "lateral flexion to left",
  ],
} as const;

// ─── Relieving Factors ───────────────────────────────────────────────

const RELIEVING_WITH_MEDICATIONS = [
  "Moving around",
  "Changing positions",
  "Stretching",
  "Resting",
  "Lying down",
  "Applying heating pad",
  "Applying ice pad",
  "Leaning forward onto something",
  "Using of joint support",
  "Massage",
  "Medications",
] as const;

const RELIEVING_WITHOUT_MEDICATIONS = [
  "Moving around",
  "Changing positions",
  "Stretching",
  "Resting",
  "Lying down",
  "Applying heating pad",
  "Applying ice pad",
  "Leaning forward onto something",
  "Using of joint support",
  "Massage",
] as const;

export const TEMPLATE_RELIEVING: Record<BodyPartKey, readonly string[]> = {
  LBP: RELIEVING_WITH_MEDICATIONS,
  NECK: RELIEVING_WITHOUT_MEDICATIONS,
  SHOULDER: RELIEVING_WITHOUT_MEDICATIONS,
  KNEE: RELIEVING_WITH_MEDICATIONS,
  ELBOW: RELIEVING_WITHOUT_MEDICATIONS,
  HIP: RELIEVING_WITH_MEDICATIONS,
  THIGH: RELIEVING_WITHOUT_MEDICATIONS,
} as const;

// ─── Causative Factors ───────────────────────────────────────────────

const CAUSATIVES_FULL = [
  "age related/degenerative changes",
  "expose to the cold air for more than 20 mins",
  "live in too cold environment",
  "weather change",
  "poor sleep",
  "over used due to heavy household chores",
  "over used due to nature of work",
  "excessive used of phone/tablet",
  "overworking in computer",
  "prolong walking",
  "prolong sitting",
  "longtime driving",
  "sitting over 30 mins with bad posture",
  "climb too much stairs",
  "intense excise",
  "lifting too much weight",
  "hurt myself during exercise",
  "repetitive injury from past work",
  "repetitive strain from activities in the past",
  "strain when pick up heavy object from floor",
  "sprain when pick up heavy object from floor",
  "recent sprain",
  "sprain",
  "fell (no sign of fracture)",
] as const;

const CAUSATIVES_KNEE = [
  "age related/degenerative changes",
  "expose to the cold air for more than 20 mins",
  "live in too cold environment",
  "poor sleep",
  "over used due to heavy household chores",
  "over used due to nature of work",
  "overworking in computer",
  "prolong walking",
  "intense excise",
  "lifting too much weight",
  "repetitive injury from past work",
  "repetitive strain from activities in the past",
  "strain when pick up heavy object from floor",
  "sprain when pick up heavy object from floor",
  "recent sprain",
  "sprain",
  "Recent fall (no sign of fracture)",
  "Inactive lifestyle",
  "Bad Posture",
  "weather changed/cold weather",
] as const;

const CAUSATIVES_HIP = [
  "age related/degenerative changes",
  "expose to the cold air for more than 20 mins",
  "live in too cold environment",
  "poor sleep",
  "over used due to heavy household chores",
  "over used due to nature of work",
  "overworking in computer",
  "prolong walking",
  "intense excise",
  "lifting too much weight",
  "repetitive injury from past work",
  "repetitive strain from activities in the past",
  "strain when pick up heavy object from floor",
  "sprain when pick up heavy object from floor",
  "recent sprain",
  "sprain",
  "Recent fall (no sign of fracture)",
  "Inactive lifestyle",
  "Bad Posture",
] as const;

export const TEMPLATE_CAUSATIVES: Record<BodyPartKey, readonly string[]> = {
  LBP: CAUSATIVES_FULL,
  NECK: CAUSATIVES_FULL,
  SHOULDER: CAUSATIVES_FULL,
  KNEE: CAUSATIVES_KNEE,
  ELBOW: CAUSATIVES_FULL,
  HIP: CAUSATIVES_HIP,
  THIGH: CAUSATIVES_FULL,
} as const;
